Revert "Merge pull request #72 from searxng/dependabot/pip/master/jinja2-3.0.0"
This reverts commit a97e366fa2230310fca9a624a8739431d99ff10d, reversing
changes made to 9dc716d58f72dfe36e664e2e94b0941f0eb9aa3d.

We can't upgrade to jinja2==3.0.0 until Sphinx 4.1.0 has been released [1][2]

ERROR: Cannot install -r /share/searx/requirements-dev.txt (line 11) and jinja2==3.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested jinja2==3.0.0
    sphinx 4.0.1 depends on Jinja2<3.0 and >=2.3

[1] https://github.com/sphinx-doc/sphinx/issues/9088#issuecomment-831020758
[2] https://github.com/sphinx-doc/sphinx/pull/9161

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>